### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by bjsi** [voidtriangle/queue-motivator#1]
- A new popup opens each time you answer a card causing the app to become laggy
![image](https://github.com/voidtriangle/queue-motivator/assets/58147075/d5c84c55-798b-4f08-b924-9d16ca41e8a9)
![image](https://github.com/voidtriangle/queue-motivator/assets/58147075/7c980a7d-efa4-4599-aef0-80e470fde17c)
`openFloatingWidget` returns the id of the floating widget. You should pass that to the `closeFloatingWidget` function
- Please reupload once fixed, the plugin works great apart from that small issue :)

**Comment by voidtriangle** [comment]
Resolved
