### ISSUE TITLE
Widget location

### ISSUE THREAD

**Issue by hugomarins** [voidtriangle/queue-motivator#2]
In your Index.tsx file, I saw that the location of the widget is fixed in relation to ".rn-queue__show-answer-btn":

![image](https://github.com/voidtriangle/queue-motivator/assets/54500828/d6211a1f-46d2-4ad2-8691-eb34a7aa205a)

I suggest you considering fixing it in relation to ".rn-queue__top-bar" instead, to ensure it does not cover the queue, like below:

![image](https://github.com/voidtriangle/queue-motivator/assets/54500828/cb3b024b-cc96-4c6d-afc4-6450425464aa)

And also set "left" to zero or another value that would not misalign the popup.

Thanks

**Comment by voidtriangle** [comment]
Please update the plugin, if still not working then uninstall  and reinstall

![image](https://github.com/voidtriangle/queue-motivator/assets/107706537/162421d5-3511-4db0-ac2e-a70b43934783)

**Comment by hugomarins** [comment]
Thanks! Perfect.
